lab = 3.64
parcial = 4.92

total = 8.56

porcentaje final = 2.8

RESTORE DATABASE EmpresaDB_Migrada
FROM DISK = 'C:\Backup\EmpresaDB_Migracion.bak'
WITH MOVE 'EmpresaDB' TO 'C:\SQLData\EmpresaDB_Migrada.mdf',
MOVE 'EmpresaDB_log' TO 'C:\SQLLogs\EmpresaDB_Migrada.ldf', 
REPLACE;

RESTORE FILELISTONLY FROM DISK = 'C:\Backup\EmpresaDB_Migracion.bak';

SELECT * FROM EmpresaDB_Migrada.sys.tables;

USE master
EXEC sp_detach_db 'EmpresaDB';

CREATE DATABASE EmpresaDB
ON (FILENAME = 'C:\SQLData\EmpresaDB.mdf'),
   (FILENAME = 'C:\SQLLogs\EmpresaDB_log.ldf')
FOR ATTACH;

SELECT COUNT (*) FROM Clientes;


DBCC CHECKDB('EmpresaDB');

SELECT TOP 10 * FROM Ventas;